export const teamAbbreviations: { [key: string]: string } = {
  'New England Patriots': 'NE',
  'New York Jets': 'NYJ',
  'Buffalo Bills': 'BUF',
  'Miami Dolphins': 'MIA',
  'Baltimore Ravens': 'BAL',
  'Pittsburgh Steelers': 'PIT',
  'Cleveland Browns': 'CLE',
  'Cincinnati Bengals': 'CIN',
  'Houston Texans': 'HOU',
  'Indianapolis Colts': 'IND',
  'Jacksonville Jaguars': 'JAX',
  'Tennessee Titans': 'TEN',
  'Kansas City Chiefs': 'KC',
  'Los Angeles Chargers': 'LAC',
  'Denver Broncos': 'DEN',
  'Las Vegas Raiders': 'LV',
  'Dallas Cowboys': 'DAL',
  'Philadelphia Eagles': 'PHI',
  'New York Giants': 'NYG',
  'Washington Commanders': 'WAS',
  'Green Bay Packers': 'GB',
  'Minnesota Vikings': 'MIN',
  'Chicago Bears': 'CHI',
  'Detroit Lions': 'DET',
  'Tampa Bay Buccaneers': 'TB',
  'New Orleans Saints': 'NO',
  'Atlanta Falcons': 'ATL',
  'Carolina Panthers': 'CAR',
  'San Francisco 49ers': 'SF',
  'Seattle Seahawks': 'SEA',
  'Los Angeles Rams': 'LAR',
  'Arizona Cardinals': 'ARI'
};

export const NBA = {
    BOS: "Boston Celtics",
    BKN: "Brooklyn Nets",
    NYK: "New York Knicks",
    PHI: "Philadelphia 76ers",
    TOR: "Toronto Raptors",
    CHI: "Chicago Bulls",
    CLE: "Cleveland Cavaliers",
    DET: "Detroit Pistons",
    IND: "Indiana Pacers",
    MIL: "Milwaukee Bucks",
    ATL: "Atlanta Hawks",
    CHA: "Charlotte Hornets",
    MIA: "Miami Heat",
    ORL: "Orlando Magic",
    WAS: "Washington Wizards",
    DEN: "Denver Nuggets",
    MIN: "Minnesota Timberwolves",
    OKC: "Oklahoma City Thunder",
    POR: "Portland Trail Blazers",
    UTA: "Utah Jazz",
    GSW: "Golden State Warriors",
    LAC: "Los Angeles Clippers",
    LAL: "Los Angeles Lakers",
    PHX: "Phoenix Suns",
    SAC: "Sacramento Kings",
    DAL: "Dallas Mavericks",
    HOU: "Houston Rockets",
    MEM: "Memphis Grizzlies",
    NOP: "New Orleans Pelicans",
    SAS: "San Antonio Spurs"
} as const; 

export const NCAAF = {
    // ACC
    BC: "Boston College",
    CLEM: "Clemson",
    DUKE: "Duke",
    FSU: "Florida State",
    GT: "Georgia Tech",
    LOU: "Louisville",
    MIA: "Miami (FL)",
    UNC: "North Carolina",
    NCSU: "NC State",
    PITT: "Pittsburgh",
    SYR: "Syracuse",
    UVA: "Virginia",
    VT: "Virginia Tech",
    WAKE: "Wake Forest",

    // American Athletic
    CIN: "Cincinnati",
    ECU: "East Carolina",
    HOU: "Houston",
    MEM: "Memphis",
    NAVY: "Navy",
    SMU: "SMU",
    USF: "South Florida",
    TEM: "Temple",
    TUL: "Tulane",
    TLSA: "Tulsa",
    UCF: "UCF",

    // Big 12
    BAY: "Baylor",
    BYU: "BYU",
    ISU: "Iowa State",
    KU: "Kansas",
    KSU: "Kansas State",
    OU: "Oklahoma",
    OKST: "Oklahoma State",
    TCU: "TCU",
    TEX: "Texas",
    TTU: "Texas Tech",
    WVU: "West Virginia",

    // Big Ten
    ILL: "Illinois",
    IND: "Indiana",
    IOWA: "Iowa",
    MD: "Maryland",
    MICH: "Michigan",
    MSU: "Michigan State",
    MINN: "Minnesota",
    NEB: "Nebraska",
    NU: "Northwestern",
    OSU: "Ohio State",
    PSU: "Penn State",
    PUR: "Purdue",
    RUT: "Rutgers",
    WISC: "Wisconsin",

    // Conference USA
    CHAR: "Charlotte",
    FAU: "Florida Atlantic",
    FIU: "FIU",
    LIB: "Liberty",
    LT: "Louisiana Tech",
    MTSU: "Middle Tennessee",
    NMSU: "New Mexico State",
    SHSU: "Sam Houston",
    UTEP: "UTEP",
    WKU: "Western Kentucky",

    // MAC
    AKR: "Akron",
    BALL: "Ball State",
    BGSU: "Bowling Green",
    BUFF: "Buffalo",
    CMU: "Central Michigan",
    EMU: "Eastern Michigan",
    KENT: "Kent State",
    "M-OH": "Miami (OH)",
    NIU: "Northern Illinois",
    OHIO: "Ohio",
    TOL: "Toledo",
    WMU: "Western Michigan",

    // Mountain West
    AFA: "Air Force",
    BSU: "Boise State",
    CSU: "Colorado State",
    FRES: "Fresno State",
    HAW: "Hawaii",
    NEV: "Nevada",
    UNM: "New Mexico",
    SDSU: "San Diego State",
    SJSU: "San Jose State",
    UNLV: "UNLV",
    USU: "Utah State",
    WYO: "Wyoming",

    // Pac-12
    ARIZ: "Arizona",
    ASU: "Arizona State",
    CAL: "California",
    COL: "Colorado",
    ORE: "Oregon",
    ORST: "Oregon State",
    STAN: "Stanford",
    UCLA: "UCLA",
    USC: "USC",
    UTAH: "Utah",
    WASH: "Washington",
    WSU: "Washington State",

    // SEC
    ALA: "Alabama",
    ARK: "Arkansas",
    AUB: "Auburn",
    FLA: "Florida",
    UGA: "Georgia",
    UK: "Kentucky",
    LSU: "LSU",
    MSST: "Mississippi State",
    MIZ: "Missouri",
    MISS: "Ole Miss",
    SCAR: "South Carolina",
    TENN: "Tennessee",
    TAMU: "Texas A&M",
    VAN: "Vanderbilt",

    // Sun Belt
    APP: "Appalachian State",
    ARST: "Arkansas State",
    CCU: "Coastal Carolina",
    GASO: "Georgia Southern",
    GSU: "Georgia State",
    JMU: "James Madison",
    ULL: "Louisiana",
    MRSH: "Marshall",
    ODU: "Old Dominion",
    USA: "South Alabama",
    USM: "Southern Miss",
    TXST: "Texas State",
    TROY: "Troy",
    ULM: "ULM",

    // Independents
    ARMY: "Army",
    ND: "Notre Dame",
    CONN: "UConn"
} as const; 

export const NHL = {
    // Atlantic Division
    BOS: "Boston Bruins",
    BUF: "Buffalo Sabres",
    DET: "Detroit Red Wings",
    FLA: "Florida Panthers",
    MTL: "Montreal Canadiens",
    OTT: "Ottawa Senators",
    TBL: "Tampa Bay Lightning",
    TOR: "Toronto Maple Leafs",

    // Metropolitan Division
    CAR: "Carolina Hurricanes",
    CBJ: "Columbus Blue Jackets",
    NJD: "New Jersey Devils",
    NYI: "New York Islanders",
    NYR: "New York Rangers",
    PHI: "Philadelphia Flyers",
    PIT: "Pittsburgh Penguins",
    WSH: "Washington Capitals",

    // Central Division
    ARI: "Arizona Coyotes",
    CHI: "Chicago Blackhawks",
    COL: "Colorado Avalanche",
    DAL: "Dallas Stars",
    MIN: "Minnesota Wild",
    NSH: "Nashville Predators",
    STL: "St. Louis Blues",
    WPG: "Winnipeg Jets",

    // Pacific Division
    ANA: "Anaheim Ducks",
    CGY: "Calgary Flames",
    EDM: "Edmonton Oilers",
    LAK: "Los Angeles Kings",
    SJS: "San Jose Sharks",
    SEA: "Seattle Kraken",
    VAN: "Vancouver Canucks",
    VGK: "Vegas Golden Knights"
} as const; 