name: Fetch Odds Data

on:
  schedule:
    # Run every hour from 6am to 11:59pm EST (11:00 - 04:59 UTC)
    - cron: '0 11-23,0-4 * * *'  # UTC times
  # Optional: Allow manual triggering
  workflow_dispatch:

jobs:
  fetch-odds:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install Dependencies
        run: npm install firebase-admin axios
        
      - name: Create Secret Files
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > service-account.json
          echo '${{ secrets.VITE_ODDS_API_KEY }}' > odds-api-key.txt
          cat service-account.json  # Debug: Print the content to check
          
      - name: Create Fetch Script
        run: |
          cat > fetch-odds.mjs << 'EOL'
          import { initializeApp, cert } from 'firebase-admin/app';
          import { getFirestore } from 'firebase-admin/firestore';
          import axios from 'axios';
          import { readFileSync } from 'fs';
          
          try {
            const serviceAccountContent = readFileSync('./service-account.json', 'utf8');
            console.log('Service account content:', serviceAccountContent); // Debug
            const serviceAccount = JSON.parse(serviceAccountContent);
            const apiKey = readFileSync('./odds-api-key.txt', 'utf8').trim();
            
            initializeApp({
              credential: cert(serviceAccount)
            });
            
            const db = getFirestore();
            
            async function fetchOdds() {
              try {
                const response = await axios.get('https://api.the-odds-api.com/v4/sports/americanfootball_nfl/odds/', {
                  params: {
                    apiKey,
                    regions: 'us,us2',
                    markets: 'h2h,spreads,totals',
                    oddsFormat: 'american',
                    includeLinks: true
                  }
                });
            
                await db.collection('odds').add({
                  data: response.data,
                  timestamp: new Date()
                });
            
                console.log('Successfully fetched and saved odds data');
              } catch (error) {
                console.error('Error in fetchOdds:', error);
                process.exit(1);
              }
            }
            
            fetchOdds();
          } catch (error) {
            console.error('Error in setup:', error);
            process.exit(1);
          }
          EOL
          
      - name: Fetch Odds Data
        run: node fetch-odds.mjs 