name: Fetch Odds Data

on:
  schedule:
    # Run every 6 hours (at 00:00, 06:00, 12:00, and 18:00 UTC)
    - cron: '0 0,6,12,18 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  fetch-odds:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install Dependencies
        run: npm install firebase-admin axios
        
      - name: Debug Environment Variables
        run: |
          echo "PROJECT_ID: ${VITE_FIREBASE_PROJECT_ID}"
          echo "PRIVATE_KEY_ID exists: ${{ secrets.VITE_FIREBASE_PRIVATE_KEY_ID != '' }}"
          echo "PRIVATE_KEY exists: ${{ secrets.VITE_FIREBASE_PRIVATE_KEY != '' }}"
          echo "CLIENT_EMAIL: ${VITE_FIREBASE_CLIENT_EMAIL}"
          echo "CLIENT_ID exists: ${{ secrets.VITE_FIREBASE_CLIENT_ID != '' }}"
          echo "CERT_URL exists: ${{ secrets.VITE_FIREBASE_CERT_URL != '' }}"
          echo "ODDS_API_KEY exists: ${{ secrets.VITE_ODDS_API_KEY != '' }}"
          echo "ODDS_API_KEY_2 exists: ${{ secrets.VITE_ODDS_API_KEY_2 != '' }}"
        env:
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_PRIVATE_KEY_ID: ${{ secrets.VITE_FIREBASE_PRIVATE_KEY_ID }}
          VITE_FIREBASE_PRIVATE_KEY: ${{ secrets.VITE_FIREBASE_PRIVATE_KEY }}
          VITE_FIREBASE_CLIENT_EMAIL: ${{ secrets.VITE_FIREBASE_CLIENT_EMAIL }}
          VITE_FIREBASE_CLIENT_ID: ${{ secrets.VITE_FIREBASE_CLIENT_ID }}
          VITE_FIREBASE_CERT_URL: ${{ secrets.VITE_FIREBASE_CERT_URL }}
          VITE_ODDS_API_KEY: ${{ secrets.VITE_ODDS_API_KEY }}
          VITE_ODDS_API_KEY_2: ${{ secrets.VITE_ODDS_API_KEY_2 }}
      - name: Fetch Odds Data
        env:
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_PRIVATE_KEY_ID: ${{ secrets.VITE_FIREBASE_PRIVATE_KEY_ID }}
          VITE_FIREBASE_PRIVATE_KEY: ${{ secrets.VITE_FIREBASE_PRIVATE_KEY }}
          VITE_FIREBASE_CLIENT_EMAIL: ${{ secrets.VITE_FIREBASE_CLIENT_EMAIL }}
          VITE_FIREBASE_CLIENT_ID: ${{ secrets.VITE_FIREBASE_CLIENT_ID }}
          VITE_FIREBASE_CERT_URL: ${{ secrets.VITE_FIREBASE_CERT_URL }}
          VITE_ODDS_API_KEY: ${{ secrets.VITE_ODDS_API_KEY }}
          VITE_ODDS_API_KEY_2: ${{ secrets.VITE_ODDS_API_KEY_2 }}
        run: node scripts/fetchOdds.js

